/**
 * frontend/src/components/wizard/InfraChatPanel.tsx
 *
 * AI_INFRA_CONVERSATIONAL_PROVISIONING_PLAN.md §7 (Phase F, Stage A) — the chat surface for the Infra
 * Architect Agent. Every assistant message here is generated by lib/infraChat.ts from a REAL InfraDraft
 * (a real Groq-backed proposal, a real edit, a real cost/policy result) — this component only renders the
 * conversation, it never itself calls an AI or invents text. Message-bubble layout intentionally mirrors
 * ChatOpsPanel.tsx's existing convention (right-aligned user bubbles, left-aligned assistant bubbles) so
 * this doesn't invent a fourth visual language for "chat" in this app.
 */
import { useRef, useEffect, useState, type ReactNode } from "react";
import { Loader2, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { InfraChatMessage } from "@/lib/infraChat";

export function InfraChatPanel({
  messages, onSend, busy, actions, footer,
}: {
  messages: InfraChatMessage[];
  onSend: (text: string) => void;
  busy: boolean;
  /** Inline quick-action buttons/dialogs (e.g. "Add a component", "Use existing resources") shown above the input. */
  actions?: ReactNode;
  /** Rendered below the message list once the human is ready to move past the chat (e.g. "Looks good, continue"). */
  footer?: ReactNode;
}) {
  const [text, setText] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages.length, busy]);

  function submit() {
    const trimmed = text.trim();
    if (!trimmed || busy) return;
    onSend(trimmed);
    setText("");
  }

  return (
    <div className="space-y-3" data-testid="infra-chat-panel">
      <div ref={scrollRef} className="max-h-96 space-y-3 overflow-y-auto rounded-md border bg-muted/10 p-3">
        {messages.map((m) => (
          <div
            key={m.id}
            className={
              m.role === "user"
                ? "ml-auto w-fit max-w-[85%] rounded-lg bg-primary/10 px-3 py-1.5 text-sm text-foreground"
                : "flex w-fit max-w-[90%] items-start gap-2"
            }
          >
            {m.role === "assistant" && <Sparkles className="mt-1 h-3.5 w-3.5 shrink-0 text-primary" />}
            <span className={m.role === "assistant" ? "rounded-lg border bg-background px-3 py-1.5 text-sm" : undefined}>
              {m.content}
            </span>
          </div>
        ))}
        {busy && (
          <div className="flex w-fit items-center gap-1.5 rounded-lg border bg-background px-3 py-1.5 text-xs text-muted-foreground">
            <Loader2 className="h-3 w-3 animate-spin" /> Thinking…
          </div>
        )}
      </div>

      {actions && <div className="flex flex-wrap items-center gap-2">{actions}</div>}

      <form
        className="flex items-center gap-2"
        onSubmit={(e) => {
          e.preventDefault();
          submit();
        }}
      >
        <Input
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder='e.g. "add a Redis cache" or "make the database Multi-AZ"'
          disabled={busy}
          className="h-9 text-sm"
        />
        <Button type="submit" size="sm" className="h-9 gap-1" disabled={busy || !text.trim()}>
          <Send className="h-3.5 w-3.5" />
        </Button>
      </form>

      {footer}
    </div>
  );
}
