"""
shared/provisioning/aws_session.py

Backlog #3 - bring-your-own-AWS-account. Turns an optional `connection` ({"role_arn", "external_id"}) into a
boto3 client: with no connection, the platform's own credentials (today's behaviour); with one, credentials
from `sts:AssumeRole` into the CUSTOMER's account.

Security shape (AWS's own third-party-access guidance, and how SaaS vendors such as Datadog do it):
  * ExternalId is generated by the PLATFORM per customer (never chosen by them), high-entropy, and passed on
    every AssumeRole - it is what stops the confused-deputy attack where customer A points the platform at
    customer B's role ARN.
  * Sessions are short (15 min default) and never cached past their expiry.
  * The customer's role, not this code, decides what is possible: least privilege lives in the role template
    (services/api-gateway/src/aws_connection_template.py).

Pure boto3, synchronous - callers use asyncio.to_thread.
"""
import threading
import time

import boto3
import structlog
from botocore.exceptions import ClientError

from shared.provisioning.aws_arn import parse_role_arn  # noqa: F401  (re-exported: api-gateway imports it from aws_arn directly)

logger = structlog.get_logger(__name__)

SESSION_SECONDS = 900  # the AssumeRole minimum: keep the blast radius of a leaked credential small
_REFRESH_MARGIN_SECONDS = 60
SESSION_NAME = "smartcd-platform"

_cache: dict[tuple[str, str], tuple[float, dict]] = {}
_cache_lock = threading.Lock()


class ConnectionError_(Exception):
    """The customer's role could not be assumed (bad ARN, wrong ExternalId, trust policy, revoked...)."""


def _assume(role_arn: str, external_id: str) -> dict:
    """Fresh credentials for the role (cached until shortly before expiry)."""
    key = (role_arn, external_id)
    now = time.time()
    with _cache_lock:
        cached = _cache.get(key)
        if cached and cached[0] - _REFRESH_MARGIN_SECONDS > now:
            return cached[1]
    try:
        resp = boto3.client("sts").assume_role(
            RoleArn=role_arn, RoleSessionName=SESSION_NAME, ExternalId=external_id, DurationSeconds=SESSION_SECONDS,
        )
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "")
        # AccessDenied covers a wrong ExternalId, a trust policy that doesn't name the platform, and a deleted role
        # alike - AWS deliberately doesn't say which, and neither do we (no probing oracle for an attacker).
        logger.warning("aws_assume_role_failed", role_arn=role_arn, code=code)
        raise ConnectionError_(
            f"Could not assume {role_arn} ({code or 'error'}). Check the role's trust policy names this platform's "
            "account and requires the ExternalId shown when the connection was created."
        ) from e
    creds = resp["Credentials"]
    value = {
        "aws_access_key_id": creds["AccessKeyId"],
        "aws_secret_access_key": creds["SecretAccessKey"],
        "aws_session_token": creds["SessionToken"],
    }
    with _cache_lock:
        _cache[key] = (creds["Expiration"].timestamp(), value)
    return value


def client(service: str, region: str, connection: dict | None = None):
    """boto3 client for `service`: the platform's own credentials, or the customer's role when `connection` is given."""
    if not connection:
        return boto3.client(service, region_name=region)
    return boto3.client(service, region_name=region, **_assume(connection["role_arn"], connection["external_id"]))


def verify_connection(role_arn: str, external_id: str) -> dict:
    """
    Assumes the role and asks STS who we are. Returns {"account_id", "arn"}. Raises ValueError for a malformed
    ARN and ConnectionError_ for anything AWS refuses. (A role in the platform's own account is allowed: without a
    connection every tenant already uses that account, so it grants nothing new - and it is how the mechanism is
    tested end to end without a second AWS account.)
    """
    expected_account = parse_role_arn(role_arn)
    creds = _assume(role_arn, external_id)
    ident = boto3.client("sts", **creds).get_caller_identity()
    if ident["Account"] != expected_account:
        raise ConnectionError_(f"Assumed a role in account {ident['Account']} but the ARN names {expected_account}.")
    return {"account_id": ident["Account"], "arn": ident["Arn"]}


def platform_account_id() -> str:
    return boto3.client("sts").get_caller_identity()["Account"]


def _clear_cache_for_tests() -> None:
    with _cache_lock:
        _cache.clear()
