"""Backlog #3 (bring-your-own-AWS-account): `aws_connections` - a tenant's connection to THEIR OWN AWS account
via a cross-account IAM role, and `infra_build_state.aws_connection_id` - which connection (if any) a draft
provisions into. NULL means the platform's own account (today's behaviour), so existing rows are unaffected.

The FK is ON DELETE RESTRICT, deliberately NOT SET NULL: NULL means "the platform's own account", so SET NULL
would silently repoint a deleted connection's drafts (a later status poll, change set or execute) at the WRONG
account. A connection that any draft still uses cannot be deleted.

`external_id` is generated by the platform (never chosen by the customer) - the per-customer value that
prevents the confused-deputy attack (see shared/provisioning/aws_session.py). `role_arn` is NULL until the
customer has created the role and the platform has verified it.

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0019"
down_revision: Union[str, None] = "0018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS aws_connections (
                connection_id  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                tenant_id      UUID        NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
                name           TEXT        NOT NULL,
                external_id    TEXT        NOT NULL,
                role_arn       TEXT,
                aws_account_id TEXT,
                default_region TEXT        NOT NULL DEFAULT 'us-east-1',
                status         TEXT        NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'VERIFIED', 'FAILED')),
                status_reason  TEXT,
                verified_at    TIMESTAMPTZ,
                created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (tenant_id, name)
            )
            """
        )
    )
    op.execute(sa.text("ALTER TABLE aws_connections ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text("ALTER TABLE aws_connections FORCE ROW LEVEL SECURITY"))
    # PERMISSIVE (no `AS RESTRICTIVE`) - see CLAUDE.md's RLS trap.
    op.execute(
        sa.text(
            """
            DROP POLICY IF EXISTS tenant_isolation_aws_connections ON aws_connections;
            CREATE POLICY tenant_isolation_aws_connections ON aws_connections
                FOR ALL
                USING (tenant_id = current_setting('app.active_tenant_id', true)::uuid)
            """
        )
    )
    # A table added by a migration needs its own grant (schema.sql's ALL TABLES grant only covered tables that existed then).
    op.execute(sa.text("GRANT SELECT, INSERT, UPDATE, DELETE ON aws_connections TO app_user"))
    op.execute(
        sa.text(
            "ALTER TABLE infra_build_state ADD COLUMN IF NOT EXISTS aws_connection_id UUID "
            "REFERENCES aws_connections(connection_id) ON DELETE RESTRICT"
        )
    )


def downgrade() -> None:
    op.execute(sa.text("ALTER TABLE infra_build_state DROP COLUMN IF EXISTS aws_connection_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS aws_connections"))
