"""
services/policy-controller/src/actuation_executor.py

Transactional Python Kubernetes client weight updates with NO pod restarts.
Spec §5.3.

Uses JSON PATCH (RFC 6902) on Gateway API HTTPRoute resource.
"""
from kubernetes import client, config as k8s_config
from kubernetes.client.rest import ApiException
import structlog
from shared import eks_auth
from src.audit_writer import record_actuation

logger = structlog.get_logger(__name__)

GROUP = "gateway.networking.k8s.io"
VERSION = "v1"
PLURAL = "httproutes"

# Fallback target used only when a caller (or an older, pre-Phase-3 pipeline
# registration) doesn't supply an explicit actuation target — kept so the
# original single-service demo pipeline keeps working unchanged.
DEFAULT_NAMESPACE = "production"
DEFAULT_ROUTE_NAME = "payment-service-route"
DEFAULT_CANARY_DEPLOYMENT = "payment-service-canary"
DEFAULT_BASELINE_DEPLOYMENT = "payment-service-baseline"


def _load_kube():
    eks_kube_config = eks_auth.get_eks_kube_client_config()
    if eks_kube_config:
        k8s_config.load_kube_config_from_dict(eks_kube_config)
        return
    try:
        k8s_config.load_incluster_config()
    except Exception:
        k8s_config.load_kube_config()


async def update_traffic_weights(
    pipeline_run_id: str,
    canary_weight: int,
    baseline_weight: int,
    authorized_by: str,
    route_name: str = DEFAULT_ROUTE_NAME,
    namespace: str = DEFAULT_NAMESPACE,
    tenant_id: str | None = None,
    db=None,
    verdict_status: str | None = None,
    confidence: float | None = None,
) -> dict:
    """
    THE ONLY FUNCTION IN THE ENTIRE SYSTEM permitted to mutate Kubernetes routing.
    Called exclusively after opa_evaluator.py returns allow_action=True AND
    verdict_verifier.py has confirmed the verdict's HMAC signature (§8.3).

    Uses a JSON PATCH (not a full replace) so it is transactional and idempotent —
    applying the same patch twice produces the same end state with no side effects.

    `route_name`/`namespace` identify WHICH service's HTTPRoute to patch — every
    onboarded service gets its own, generated by Phase 3's manifest generator
    (§03-multi-service-onboarding.md), so two services' rollouts never touch
    each other's traffic weights.
    """
    _load_kube()
    api_client = client.ApiClient()

    patch_body = [
        {
            "op": "replace",
            "path": "/spec/rules/0/backendRefs/0/weight",
            "value": baseline_weight,
        },
        {
            "op": "replace",
            "path": "/spec/rules/0/backendRefs/1/weight",
            "value": canary_weight,
        },
    ]

    try:
        # CustomObjectsApi.patch_namespaced_custom_object hardcodes
        # Content-Type: application/merge-patch+json in this client version
        # (kubernetes==29.0.0) and doesn't accept a content-type override —
        # a merge patch would need to resend the whole `rules[0]` object
        # (including `matches`) or lose it, since JSON Merge Patch replaces
        # arrays wholesale rather than patching by index. Calling the
        # low-level API client directly keeps this a true RFC 6902 JSON
        # Patch: transactional, and touching only the two weight fields.
        result = api_client.call_api(
            f"/apis/{GROUP}/{VERSION}/namespaces/{namespace}/{PLURAL}/{route_name}",
            "PATCH",
            header_params={"Content-Type": "application/json-patch+json", "Accept": "application/json"},
            body=patch_body,
            auth_settings=["BearerToken"],
            response_type="object",
            _preload_content=True,
        )
        logger.info(
            "traffic_weights_updated",
            pipeline_run_id=pipeline_run_id,
            canary_weight=canary_weight,
            baseline_weight=baseline_weight,
        )
    except ApiException as e:
        logger.error("weight_update_failed", error=str(e), pipeline_run_id=pipeline_run_id)
        raise

    await record_actuation(
        pipeline_run_id=pipeline_run_id,
        action="WEIGHT_UPDATE",
        canary_weight=canary_weight,
        baseline_weight=baseline_weight,
        authorized_by=authorized_by,
        tenant_id=tenant_id,
        db=db,
        verdict=verdict_status,
        confidence=confidence,
    )
    return {"canary_weight": canary_weight, "baseline_weight": baseline_weight}


async def emergency_rollback(
    pipeline_run_id: str,
    authorized_by: str,
    route_name: str = DEFAULT_ROUTE_NAME,
    namespace: str = DEFAULT_NAMESPACE,
    canary_deployment_name: str = DEFAULT_CANARY_DEPLOYMENT,
    tenant_id: str | None = None,
    db=None,
    verdict_status: str | None = None,
    confidence: float | None = None,
) -> dict:
    """Idempotent — safe to call twice. Sets weight to 0 AND scales replicas to 0."""
    await update_traffic_weights(
        pipeline_run_id,
        canary_weight=0,
        baseline_weight=100,
        authorized_by=authorized_by,
        route_name=route_name,
        namespace=namespace,
        tenant_id=tenant_id,
        db=db,
        verdict_status=verdict_status,
        confidence=confidence,
    )

    _load_kube()
    apps_v1 = client.AppsV1Api()
    try:
        apps_v1.patch_namespaced_deployment_scale(
            name=canary_deployment_name,
            namespace=namespace,
            body={"spec": {"replicas": 0}},
        )
        logger.info("emergency_rollback_complete", pipeline_run_id=pipeline_run_id)
    except ApiException as e:
        logger.warning("scale_canary_to_zero_failed", error=str(e), pipeline_run_id=pipeline_run_id)

    await record_actuation(
        pipeline_run_id=pipeline_run_id,
        action="ROLLBACK",
        canary_weight=0,
        baseline_weight=100,
        authorized_by=authorized_by,
        tenant_id=tenant_id,
        db=db,
        verdict=verdict_status,
        confidence=confidence,
    )
    return {"status": "ROLLED_BACK"}


async def graduate_canary(
    pipeline_run_id: str,
    authorized_by: str,
    route_name: str = DEFAULT_ROUTE_NAME,
    namespace: str = DEFAULT_NAMESPACE,
    canary_deployment_name: str = DEFAULT_CANARY_DEPLOYMENT,
    baseline_deployment_name: str = DEFAULT_BASELINE_DEPLOYMENT,
    tenant_id: str | None = None,
    db=None,
) -> dict:
    """
    Real gap found live: once a canary's ramp reached 100%, nothing ever
    made that durable on the cluster — the `canary` Deployment kept serving
    all traffic while `baseline` sat idle running the ORIGINAL image
    forever. The next rollout would keep comparing against that stale
    baseline, and a config/UI record could claim a version was "live" while
    the actual baseline Deployment never ran it. This makes it real:
    reads the canary's LIVE image (not whatever tag was requested — if it
    drifted, this graduates what's actually running), copies it onto
    baseline via a strategic merge patch (Kubernetes merges the
    `containers` list by name automatically here — unlike the HTTPRoute
    case above, no JSON-Patch workaround is needed for a native Deployment
    resource), resets the route to 100% baseline once both sides run the
    same image, and idles the canary Deployment down to 0 replicas so it's
    ready to be reused as the next test's deploy target.

    Idempotent like emergency_rollback: re-running this against an
    already-graduated baseline (same image already applied, canary already
    at 0 replicas) is a no-op with no side effects.
    """
    _load_kube()
    apps_v1 = client.AppsV1Api()

    try:
        canary = apps_v1.read_namespaced_deployment(name=canary_deployment_name, namespace=namespace)
    except ApiException as e:
        logger.error("graduate_canary_read_failed", error=str(e), pipeline_run_id=pipeline_run_id)
        raise

    containers = canary.spec.template.spec.containers
    if not containers:
        raise ValueError(f"Canary deployment {canary_deployment_name} has no containers to graduate")
    canary_image = containers[0].image
    container_name = containers[0].name

    try:
        apps_v1.patch_namespaced_deployment(
            name=baseline_deployment_name,
            namespace=namespace,
            body={"spec": {"template": {"spec": {"containers": [{"name": container_name, "image": canary_image}]}}}},
        )
        logger.info(
            "baseline_image_graduated",
            pipeline_run_id=pipeline_run_id,
            baseline_deployment_name=baseline_deployment_name,
            new_image=canary_image,
        )
    except ApiException as e:
        logger.error("graduate_baseline_patch_failed", error=str(e), pipeline_run_id=pipeline_run_id)
        raise

    await update_traffic_weights(
        pipeline_run_id,
        canary_weight=0,
        baseline_weight=100,
        authorized_by=authorized_by,
        route_name=route_name,
        namespace=namespace,
        tenant_id=tenant_id,
        db=db,
    )

    try:
        apps_v1.patch_namespaced_deployment_scale(
            name=canary_deployment_name,
            namespace=namespace,
            body={"spec": {"replicas": 0}},
        )
    except ApiException as e:
        # Not fatal — the important safety-relevant change (baseline now
        # runs the graduated image, traffic is back on it) already
        # succeeded. An idle canary still holding old replicas just means
        # the next build reuses it without a fresh scale-up, which is safe.
        logger.warning("graduate_canary_scale_down_failed", error=str(e), pipeline_run_id=pipeline_run_id)

    await record_actuation(
        pipeline_run_id=pipeline_run_id,
        action="GRADUATE",
        authorized_by=authorized_by,
        tenant_id=tenant_id,
        db=db,
    )
    return {"status": "GRADUATED", "new_baseline_image": canary_image}
