/**
 * frontend/src/pages/VerificationInspector.tsx — Screen 2.
 */
import { AlertCircle, CheckCircle2, Clock, Rocket, ShieldAlert, Sparkles, XCircle } from "lucide-react";
import { useVerificationResult } from "@/hooks/useVerificationResult";
import { usePipelineEvents } from "@/hooks/usePipelineEvents";
import { useAppContext } from "@/hooks/useAppContext";
import { VerdictBadge } from "@/components/verification/VerdictBadge";
import { EvidencePanel } from "@/components/verification/EvidencePanel";
import { ConfidenceGauge } from "@/components/charts/ConfidenceGauge";
import { TrafficGauge } from "@/components/pipeline/TrafficGauge";
import { TrafficWeightChart } from "@/components/pipeline/TrafficWeightChart";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { HelpTooltip } from "@/components/help-tooltip";

// Real gap found live (2026-09-18): a non-technical user looking at
// "Composite score 100.0/100.0" sitting right next to a "DEGRADED" badge
// has no way to know those aren't contradictory — and the actual plain-
// language explanation (already real, already generated by the AI RCA
// step) lived at the very bottom of the screen, below a dense technical
// evidence panel, so it was effectively never seen. This gives an
// INSTANT, always-available plain-language headline — no AI call, no
// waiting — derived purely from the verdict status itself, so the user
// never has to interpret a raw number before understanding what happened.
// Full, static class strings only — Tailwind's build-time scanner can only
// find literal class strings, never a template-interpolated one like
// `text-${tone}`, so each tone's classes must be spelled out completely.
const TONE_CLASSES = {
  success: { card: "border-success/40 bg-success/5", icon: "text-success", headline: "text-success" },
  destructive: { card: "border-destructive/40 bg-destructive/5", icon: "text-destructive", headline: "text-destructive" },
  warning: { card: "border-warning/40 bg-warning/5", icon: "text-warning", headline: "text-warning" },
} as const;

function plainLanguageSummary(
  status: string
): { icon: typeof CheckCircle2; classes: (typeof TONE_CLASSES)[keyof typeof TONE_CLASSES]; headline: string; body: string } {
  switch (status) {
    case "HEALTHY":
      return {
        icon: CheckCircle2,
        classes: TONE_CLASSES.success,
        headline: "This version looks good",
        body: "Real traffic to the new version was compared against the current live version, and no problems were found — the platform is confident enough to keep moving forward.",
      };
    case "FAILED":
      return {
        icon: XCircle,
        classes: TONE_CLASSES.destructive,
        headline: "A real problem was found — the platform reacted automatically",
        body: "Something measurably got worse on the new version compared to what's currently live. The platform already took action on this (see below) — no one needs to react manually.",
      };
    case "DEGRADED":
      return {
        icon: Clock,
        classes: TONE_CLASSES.warning,
        headline: "Not enough real evidence yet to make a confident call",
        body: "The platform hasn't seen enough real traffic on the new version yet to be sure it's safe — so, by design, it hasn't promoted it further and hasn't rolled it back either. It's waiting for more real evidence rather than guessing.",
      };
    default:
      return {
        icon: ShieldAlert,
        classes: TONE_CLASSES.warning,
        headline: "The platform couldn't reach a confident answer in time",
        body: "Verification ran out of time without enough evidence to say healthy or failed. Nothing was auto-promoted or auto-rolled-back on an inconclusive result — this one may need a human to take a look.",
      };
  }
}

export function VerificationInspector() {
  const { pipelineRunId, deployMode } = useAppContext();
  const { verdict, metrics, rcaReport, rcaPending, isLoading, error } = useVerificationResult(pipelineRunId);
  // Phase 4: the canary ramp is only meaningful WHILE progressive_verify is
  // the active stage — same live WebSocket state Pipeline View already
  // renders, just surfaced here too so the Inspector doesn't need a trip
  // back to the other screen to see what traffic level this verdict
  // actually corresponds to.
  const { currentStage, trafficWeight, weightHistory, status: pipelineStatus } = usePipelineEvents(pipelineRunId);

  if (!pipelineRunId) {
    return <p className="text-sm text-muted-foreground">Select a pipeline run to inspect its verdict.</p>;
  }
  if (isLoading) {
    return (
      <div className="grid gap-4 md:grid-cols-2">
        <Skeleton className="h-24" />
        <Skeleton className="h-24" />
        <Skeleton className="h-40 md:col-span-2" />
      </div>
    );
  }
  if (error) {
    if (error.status === 404) {
      // Real gap found live (2026-09-15): a project's genuinely first-ever
      // deployment intentionally never produces a verdict at all — there's
      // no prior baseline to compare against yet, so canary_loop ships
      // straight to 100% and skips statistical verification entirely (see
      // worker.py). Before this, a run that had actually COMPLETED
      // successfully showed the exact same "hasn't completed (or hasn't
      // started)" message as one still genuinely in progress — confusing
      // for the one case where "no verdict" is the CORRECT, expected
      // outcome rather than something still pending.
      //
      // Real gap found live (2026-09-18): blue-green mode was added two
      // days after the message above was written, and it ALSO never
      // produces a verdict for ANY run — not just the first. Without this
      // branch, a blue-green project's 5th deploy would still say "this
      // was the project's first-ever deployment," which is simply false.
      // The underlying "no verdict" behavior is correct either way; only
      // the explanation text needs to match the real reason.
      if (pipelineStatus === "COMPLETED") {
        const isBlueGreen = deployMode === "blue_green";
        return (
          <Card className="mx-auto mt-8 max-w-lg text-center">
            <CardContent className="flex flex-col items-center gap-2 p-8 text-sm text-muted-foreground">
              <Rocket className="h-8 w-8 text-muted-foreground/60" />
              <p className="font-medium text-foreground">
                {isBlueGreen ? "Blue-Green deployment — no statistical comparison" : "First deployment — no comparison to run yet"}
              </p>
              <p>
                {isBlueGreen ? (
                  <>
                    This project uses Blue-Green deployment, which never runs statistical verification — it cuts
                    over based on real infrastructure health (target-group health checks and a live URL check)
                    instead of a baseline-vs-canary comparison. This is expected for every run on this project,
                    not just the first.
                  </>
                ) : (
                  <>
                    This was the project's first-ever deployment, so there was no prior baseline version to compare
                    it against. It shipped directly to 100% traffic with no canary step. Future deployments will run
                    the full statistical verification and progressive traffic ramp.
                  </>
                )}
              </p>
            </CardContent>
          </Card>
        );
      }
      return (
        <Card className="mx-auto mt-8 max-w-lg text-center">
          <CardContent className="flex flex-col items-center gap-2 p-8 text-sm text-muted-foreground">
            <AlertCircle className="h-8 w-8 text-muted-foreground/60" />
            No verdict published yet for this run — verification hasn't completed (or hasn't started).
          </CardContent>
        </Card>
      );
    }
    return <p className="text-sm text-destructive">Error: {error.message}</p>;
  }
  if (!verdict) return <p className="text-sm text-muted-foreground">No verification run yet.</p>;

  const plain = plainLanguageSummary(verdict.status);
  const PlainIcon = plain.icon;

  return (
    <div className="space-y-4">
      <Card className={plain.classes.card}>
        <CardContent className="flex items-start gap-3 p-4">
          <PlainIcon className={`mt-0.5 h-6 w-6 shrink-0 ${plain.classes.icon}`} />
          <div>
            <p className={`font-semibold ${plain.classes.headline}`}>{plain.headline}</p>
            <p className="mt-1 text-sm text-muted-foreground">{plain.body}</p>
            {rcaReport && <p className="mt-2 text-sm leading-relaxed">{rcaReport}</p>}
            {!rcaReport && rcaPending && (
              <p className="mt-2 text-xs text-muted-foreground">Generating a detailed explanation…</p>
            )}
          </div>
        </CardContent>
      </Card>

      {currentStage === "progressive_verify" && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">
              Canary traffic ramp
              <HelpTooltip>The live traffic-weight progression for this run — this verdict was produced at the weight shown here.</HelpTooltip>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <TrafficGauge weight={trafficWeight} status={pipelineStatus} />
            <TrafficWeightChart history={weightHistory} />
          </CardContent>
        </Card>
      )}

      <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
        Technical detail (for the numbers behind the summary above)
      </p>
      <Card className="overflow-hidden">
        <div className="flex flex-col gap-4 border-b bg-muted/20 p-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-5">
            <ConfidenceGauge confidence={verdict.confidence} />
            <div>
              <div className="flex items-center gap-2">
                <span className="text-stat text-2xl">{verdict.composite_score.toFixed(1)}</span>
                <span className="text-stat text-sm text-muted-foreground">/ 100.0</span>
                <VerdictBadge status={verdict.status} />
              </div>
              <p className="mt-1 max-w-md text-sm text-muted-foreground">
                Composite score
                <HelpTooltip>Weighted average of non-critical metrics' health (0–100). Critical-tier breaches (e.g. error rate) override this entirely with a hard FAILED — they're never diluted into an average.</HelpTooltip>{" "}
                combines all evaluated metrics; confidence
                <HelpTooltip>How much this verdict should be trusted — combines sample size vs. the N≥100 floor, variance stability between cohorts, and whether the minimum observation window has actually elapsed.</HelpTooltip>{" "}
                reflects how much this verdict should be trusted.
              </p>
              {verdict.tier1_breaches.length > 0 && (
                <p className="mt-1 text-sm font-medium text-destructive">
                  Tier-1 breaches
                  <HelpTooltip>A "tier-1" (critical) metric — like error rate — showed a statistically significant regression. This alone forces a FAILED verdict regardless of every other metric.</HelpTooltip>
                  : {verdict.tier1_breaches.join(", ")}
                </p>
              )}
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 border-t pt-3 text-code lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0">
            <div>
              <span className="block text-[11px] text-muted-foreground">Verdict ID</span>
              <span className="text-xs font-semibold">{verdict.verdict_id.slice(0, 12)}…</span>
            </div>
            <div>
              <span className="block text-[11px] text-muted-foreground">Metrics evaluated</span>
              <span className="text-xs font-semibold">{Object.keys(verdict.evidence).length}</span>
            </div>
            <div>
              <span className="block text-[11px] text-muted-foreground">Sample floor</span>
              <span className="text-xs font-semibold text-primary">N ≥ 100</span>
            </div>
          </div>
        </div>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Evidence</CardTitle>
        </CardHeader>
        <CardContent>
          <EvidencePanel evidence={metrics} />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            AI Root Cause Analysis
            <HelpTooltip>
              Generated after the platform has already acted on this verdict — this explains WHY, it never
              delays or gates the actual promote/rollback decision.
            </HelpTooltip>
          </CardTitle>
        </CardHeader>
        <CardContent>
          {rcaReport ? (
            <p className="text-sm leading-relaxed">{rcaReport}</p>
          ) : rcaPending ? (
            <p className="text-sm text-muted-foreground">Generating explanation…</p>
          ) : (
            <p className="text-sm text-muted-foreground">No explanation available for this run.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
